### ISSUE TITLE
Compatibility Shopware 6.4.8.1

### ISSUE THREAD

**Issue by nyarlatothep** [iMi-digital/shopware6-import-by-product-number#2]
Hi,
thanks for this great plugin. Sadly it stopped working with 6.4.8.1, or we did something wrong.
Any possibility for an update?

Thanks for your time.

**Comment by amenk** [comment]
Thanks for the report, do you have more details / screenshots? Which version did you use before?

**Comment by nyarlatothep** [comment]
Thanks for your fast response.
I'm trying to investigate in this topic (with my limited knowledge.) I succeeded in importing data with your plugin, but only if the products already exist in shopware. 
If i use a csv with entries that don't exist in shopware the following error is reported from the import modul for this item:

`Expected command for "Shopware\Core\Content\Product\ProductDefinition" to be "Shopware\Core\Framework\DataAbstractionLayer\Write\Command\UpdateCommand". (Got: Shopware\Core\Framework\DataAbstractionLayer\Write\Command\InsertCommand)`

In Shopware 6.4.8.1 you can choose in the profile to only "update the data" instead of creating new products for unknown entries in the csv to be imported. I guess it's a new switch, some things in the shopware import/export-behaviour did change during the last updates. Don't know if this is relevant.

Trying my best to find more information... :)

**Comment by amenk** [comment]
Okay, so which option are you using for the import?

**Comment by nyarlatothep** [comment]
I do use the following options in the profile for import/exports:
Object-Type: product
Use: Import and Export
The switch for "creating new entries" is off
The switch for "update existing entries" is on

Hope this helps.

**Comment by amenk** [comment]
Okay thanks, for the details, we will try to reproduce and fix.

As the module is free I cannot guarantee a solution time.

If you need it urgently we could plan to tackle this next week for a fee.

**Comment by amenk** [comment]
Shopware 6.4.9.0 includes the same functionality which this module provides, please have a look. This plugin will be discontinued.
